### PR TITLE
feature : Landing Page Styling with CSS

### LINKED ISSUE #1: feature : Responsive landing page for the website from the Figma Design
**Is your feature request related to a problem? Please describe.**
There is a Figma Landing Page design but it hasn't been designed with HTML and CSS. **I would like to be assigned the issue** to implement the designs with CSS and Flexbox.

**Describe the solution you'd like**
Design a aesthetic landing page with HTML, CSS, Flexbox and Grid identical to the Figma designs.
 
**Describe alternatives you've considered**
There are no alternatives needed. I can think of implementing in TailwindCSS later on.

### LINKED ISSUE #5: Vendor backend registeration using mongodb
**Is your feature request related to a problem? Please describe.**
Yes, the vendor sign-in page at present doesn't look interactive to the user. So  would like to create a issue to store the vendor data using mongodb .

**Describe the solution you'd like**
I Would like to implement a backend part to the vendor sign-in/ registration page giving it a good user friendly interface.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by vedanthv**
#### Issue Number
fixes #1 This is the second PR for the issue.

#### Describe the changes you've made
I haven't made any changes to the codebase. Styling has been added to the Landing Page whose HTML structure was designed in [this PR](https://github.com/Tech-Matrix/PRNTRS/pull/4).

#### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
`NA
`
#### Additional context
No additional context. I may switch to TailwindCSS sometime in the future.

#### Test plan (OPTIONAL BUT RECOMMENDED)
`N/A`

#### Checklist

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### Final Landing Page Screenshot
image

### CODE REVIEW

**Comment by vedanthv** [comment]
@A-HK This completes my 1 PR for the week commitment from the team's end. Please include whatever I do from now on for the `free for all week` from Monday👍. I will support my team to roll out new enhancements.

**Comment by A-HK** [comment]
Hey @vedanthv , I appreciate that you stuck to the design.
I have a couple of requests that I'd like you to implement before I merge this

1. Not a fan of the pink hover state when I go over the main div. Maybe lose the hover state here and add a hover state to the buttons [ A slightly different opacity for the buttons when hovered over perhaps ] ? 
Screenshot (623)

2. Need more whitespace for the buttons. This isn't your fault; it was there in the design, but I'd still love it if you changed the layout from this 
image

to something more like this.
image

Don't change the styling of the buttons themselves, I like the way that you've made them currently [ with all the text in one line ], but just change how they're positioned.

**Comment by A-HK** [comment]
Other than that, I think it looks good !
Again, the above are just my two cents - I wasn't involved with designing the landing page; just the vendor pages.

As soon as you make these changes, this PR will be merged !

Maybe we can look at making the actual content of the homepage and the overall navigation better a little later, in a separate issue.

**Comment by vedanthv** [comment]
Thanks for the feedback @A-HK 
> 1. Not a fan of the pink hover state when I go over the main div. Maybe lose the hover state here and add a hover state to the buttons [ A slightly different opacity for the buttons when hovered over perhaps ] ?

This can be done. What color do you want for the button on hover?

> 2. Need more whitespace for the buttons. This isn't your fault; it was there in the design, but I'd still love it if you changed the layout from this

So if I were to make the positioning the way it's in your second image, the image will be smaller. Is that okay?

**Comment by vedanthv** [comment]
> Maybe we can look at making the actual content of the homepage and the overall navigation better a little later, in a separate issue.

Can't help you the content, I'm not good at it. For the navigation, I would need the designs.

**Comment by vedanthv** [comment]
@A-HK Updated Page. Let me know if this is fine.
image

Button on Hover 
Screenshot 2021-09-17 090735

**Comment by A-HK** [comment]
Thanks @vedanthv !
Will look at it one last time and then merge after I get back from college.

**Comment by vedanthv** [comment]
> Thanks @vedanthv !
> Will look at it one last time and then merge after I get back from college.

Okay. No hurry👍

**Pull request closed without merging**
