### PR TITLE
Progressive Registration Form 2/2 : JS Functionality

### LINKED ISSUE #12: feature : Progressive Client Registration Form - Frontend
**Is your feature request related to a problem? Please describe.**

Currently there is no Client Registration Form and I would like to design and implement one with an innovative design. 

**Describe the solution you'd like**

Usually Google Forms is long and it's very long in nature. It would deviate the users attention. I would like to implement a form like **Typeform** which is progressive in nature and the user's attention doesn't deviate.

**Describe alternatives you've considered**

I have a clear plan in mind as of now and don't need to consider alternate solutions.

**Additional context**

I will add screenshots and live demo in my further PR's.

### PR DESCRIPTION
**Pull request by vedanthv**
#### Issue Number

Completely fixes #12

#### Describe the changes you've made

I have added the JavaScript functionality to the progressive registration page for the client. This feeds the questions dynamically to user and gives a good UI using DOM manipulation.

#### Describe if there is any unusual behaviour of your code ( Write `NA` if there isn't )
`NA`

#### Additional context
No additional context as such. More features can be added later

#### Test plan ( Optional but Recommended )
All the files required to test are in `PRNTRS Client/Register/dist` including the ones from PR #25.

#### Demo
⚠You can run the demo on your system only after PR #25 is merged! Here's a short demo anyhow. Had great fun building it!

**⚠Another note : I made the video before the styling on `main.html` was changed. So the color is still red**

https://user-images.githubusercontent.com/44313631/134160324-5b6fdf5a-89c6-4f26-8975-e15cb8ddf007.mp4

#### Checklist

- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by vedanthv** [comment]
@A-HK The progressive registration form code is completed. Let me know if there are any bugs, changes to be made. Else it's ready to be merged

**Comment by A-HK** [comment]
Cool will check it out in a while @vedanthv . Was a little occupied

**Comment by vedanthv** [comment]
> Cool will check it out in a while @vedanthv . Was a little occupied

No problem! Take your time! I'll help you out by reviewing other PR's when I'm free!

**Comment by A-HK** [comment]
Hey @vedanthv ! Great work  - This looks amazing !
Keep contributing :)

**Comment by vedanthv** [comment]
@A-HK what is the label `level3`?

**Comment by A-HK** [comment]
These labels are just for determining the difficulty/amount of work done in the PR.

**Pull request merged**
