### PR TITLE
goel-vanshika updated css of client sign in page

### LINKED ISSUE #5: Vendor backend registeration using mongodb
**Is your feature request related to a problem? Please describe.**
Yes, the vendor sign-in page at present doesn't look interactive to the user. So  would like to create a issue to store the vendor data using mongodb .

**Describe the solution you'd like**
I Would like to implement a backend part to the vendor sign-in/ registration page giving it a good user friendly interface.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by goel-vanshika**
Issue Number 6
fixes css of client sign in to match vendor sign in page

#### Describe the changes you've made
I made updates to the css to match vendor sign in page in the form of color matching, font styling and overall look of the page

#### Describe if there is any unusual behaviour of your code ( Write `NA` if there isn't )
NA

#### Additional context
Similar updates have been made to the html files in order to make it more harmonious with the css page

#### Test plan ( Optional but Recommended )
NA

#### Checklist
- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ]x
Screenshot 2021-09-18 at 9 58 56 PM
 The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by vedanthv** [comment]
Also @goel-vanshika , the theme of the website is `light red`, `white` and `purple`. But I notice that the color for this page is blue. I think you can make the blue elements `light red` or a shade darker. @A-HK would like your opinion on this too.

Another small note, this pull request also has html files, you can make a branch for html, add all the commits for html5 files there and then once the branch is merged, you can delete it. Then create one more branch for CSS styling, and commit the CSS files there. This would be easier to review.

**Comment by goel-vanshika** [comment]
I added it as blue to match the image that was inserted by the original creators. This will also help differentiate between the client page and vendor page. My opinion was to make the client side with blue tones and vendor with red.
This gives a direct differentiation and helps avoid confusion for everyone.
Im willing to change if needed.

**Comment by vedanthv** [comment]
> I added it as blue to match the image that was inserted by the original creators. This will also help differentiate between the client page and vendor page. My opinion was to make the client side with blue tones and vendor with red.
> This gives a direct differentiation and helps avoid confusion for everyone.
> Im willing to change if needed.

Understandable but I have come across very few websites that change color palettes from red to blue. We will take others suggestions also.

**Comment by vedanthv** [comment]
@achyuta116 Keeping you in the loop here regarding the color scheme since you are working on #9 . View the other comments for more clarity!

**Comment by A-HK** [comment]
Hey @goel-vanshika , sorry for the late reply ! While you've done an amazing job with this, it is true that the preferred colour scheme is red. I agree with you that the colour of the image is a little off, so I edited it a bit.
Is it possible to change your colour scheme now?
Printer-rafiki (1)

**Comment by goel-vanshika** [comment]
i changed the color scheme to red to match the image.
Do i commit the changes again and do a new pr now?
@A-HK thank you for the new image!!

**Comment by A-HK** [comment]
Awesome! I think you can just commit to this branch and update the very same PR.
There shouldn't be too many changes from your previous commits, so I think this'll work just fine

**Comment by goel-vanshika** [comment]
sorry due to some system shutdown issue..i'll have to recommit all the changes i made to the css and html from the beginning
ill commit those changes to the same pr tho

**Comment by vedanthv** [comment]
@goel-vanshika you can keep the PR open since you want to merge to this itself

**Comment by A-HK** [comment]
She said it would be easier to start afresh, and I was okay with that, so I gave her the go-ahead to close this

**Pull request closed without merging**
