### PR TITLE
Modified UI to be responsive, changed HTML CSS accordingly

### LINKED ISSUE #9: [BUG] UI isn't responsive on smaller width screens
**Describe the bug**
UI in the Vendor's Orders List isn't responsive and the elements stack on top of eachother

**To Reproduce**
1. Load the webpage in the browser
2. Resize the browser to see the changes

**Expected behavior**
UI should have been responsive and cleanly displayed on smaller width screens

**Screenshots**

**Desktop (please complete the following information):**
 - Browser :- Brave
 - Version :- 1.18.78

### PR DESCRIPTION
**Pull request by achyuta116**
#### Issue Number
Fixes #9 

#### Describe the changes you've made
Modified CSS to use Grid styling and changed HTML to easily update the lists dynamically from the backend.
Styled according to the Figma Designs and fixed up the header.
Can target different lists through class attributes.
Fixed HTML to be compatible with different browser widths i.e for Tablet size, Smartphone size (Mobile first).

#### Describe if there is any unusual behaviour of your code
N/A

#### Checklist
- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by A-HK** [comment]
Hey @achyuta116 , please add some screenshots of the mobile, tablet and desktop view.
This would be incredibly helpful for me to understand what's going on

**Comment by achyuta116** [comment]
Screenshots of the website in Desktop, Tablet size (x2) and mobile sized screens
Screenshot 2021-09-19 at 5 05 55 PM
Screenshot 2021-09-19 at 5 07 04 PM
Screenshot 2021-09-19 at 5 07 22 PM

Screenshot 2021-09-19 at 5 07 50 PM
@A-HK

**Comment by A-HK** [comment]
Cool. Looks great!
Just give me a while to look through the files one last time and then merge.

**Comment by A-HK** [comment]
Hey @achyuta116 , this looks absolutely perfect ! 
Thanks so much for your contribution, keep contributing 🎉

**Pull request merged**
