### PR TITLE
Payment Gateway for Client 2/2 : Implementing the Frontend for the Stripe Payment Integration

### LINKED ISSUE #26: feature : Payment Gateway Integration for the Client
**Is your feature request related to a problem? Please describe.**

Currently there is no Payment Gateway Checkout which means client can't pay the vendor. I would like to implement this using Razorpay.

**Describe the solution you'd like**

I am going to using the Razorpay NodeJS SDK, OrdersAPI and their Signature Verification functions to implement this.

**Describe alternatives you've considered**

No alternative solutions thought of so far.

**Additional context**

No additional context as such.

### PR DESCRIPTION
**Pull request by vedanthv**
#### Issue Number
fixes #26 

#### Describe the changes you've made
- Fixed the route to `mappy` in `index.js`
- Added a button and other required code to integrate Payment with Frontend `mappy` page.
- For the routes to get access to our HTML and CSS files I have added the `ejs` templates in `views` and static files in `public`

#### Describe if there is any unusual behaviour of your code ( Write `NA` if there isn't )
The CSS for the `mappy` page and Landing page after redirection does not load. This can be fixed in another PR/new issue.

#### Additional context

**The PR has 473 additions but the only crucial one is the index.js file and the mappy html changes**
#### Test plan ( Optional but Recommended )
- Get Stripe API keys from the website.
- Fork, fetch and run the `index.js` file
- Click the Payment link on `mappy.html` to initiate payment
- Use `4242 4242 4242 4242` as test card number, give any future date as expiry and any 3 digit CVV
- You should be redirected to Landing Page.

#### Checklist

- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by vedanthv** [comment]
@A-HK The styles do not load here also. I mentioned it here but forgot to do it in #29 . Again not my problem as such, there are too many stylesheets with same name Xd

**Comment by A-HK** [comment]
Just has a few merge conflicts @vedanthv, please resolve them.
Also slightly off-topic, but would love some clarification wrt [this comment](https://github.com/Tech-Matrix/PRNTRS/pull/29#issuecomment-929364324) if you haven't already, before continuing with any new PR!

**Comment by vedanthv** [comment]
> Just has a few merge conflicts @vedanthv, please resolve them. Also slightly off-topic, but would love some clarification wrt [this comment](https://github.com/Tech-Matrix/PRNTRS/pull/29#issuecomment-929364324) if you haven't already, before continuing with any new PR!

Yep Done. No Conflicts now.

**Comment by A-HK** [comment]
Keep contributing @vedanthv !

**Pull request merged**
